config/routes.rb
Rails.application.routes.draw do
  mount Motor::Admin => '/motor_admin'
  root "home#index"

  get "/publications/new", to: "publications#new", as: :new_publication # mostrar formulario de crear
  get "/publications", to: "publications#index" # listar todas
  get "/publications/:id", to: "publications#show", as: :publication # Metodo helper para poder referenciarlo en el codigo y no tener que escribir el url
  post "publications", to: "publications#create" # metodo para crear
  get "publications/:id/edit", to: "publications#edit", as: :edit_publication
  patch "publications/:id", to: "publications#update" # metodo para editar
  delete "publications/:id", to: "publications#destroy", as: :delete_publication# metodo para eliminar
  namespace :authentication, path:'', as:'' do
    resources :users, only: [:new,:create,:show, :edit, :update]
    resources :sessions, only: [:new, :create, :destroy]
  end 
  
  post "comments/:id", to: "comments#create"
  delete "comments/:id", to: "comments#destroy", as: :delete_comments# metodo para eliminar
  
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :publication
    belongs_to :user, default: -> {Current.user}

end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/publication.rb
class Publication < ApplicationRecord
    has_one_attached :image

    validates :title, presence: true
    validates :content, presence: true

    has_many :comments, dependent: :restrict_with_exception, dependent: :delete_all     
    belongs_to :user, default: -> {Current.user}
end

app/models/user.rb
class User < ApplicationRecord
    
    has_one_attached :img

    has_secure_password


    has_many :publications, dependent: :restrict_with_exception, dependent: :destroy
    has_many :comments, dependent: :restrict_with_exception, dependent: :destroy   
        
    validates :name, presence: true
    validates :lastname, presence: true
    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: true
    # validates :rol, presence: true
    # validates :blocked, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include Pagy::Backend

    before_action :set_current_user
    before_action :protect_route

    def set_current_user
        Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def protect_route
        redirect_to new_session_path unless Current.user
    end


end

app/controllers/authentication/sessions_controller.rb
class Authentication::SessionsController < ApplicationController

    skip_before_action :protect_route
    #  skip_before_action :protect_route only [:new, :create]
    
    def new
    end
    def create
        @user = User.find_by("email = :email",{email:params[:email]})

        if @user.nil?
            redirect_to new_session_path, alert: "Usuario no encontrado."
            return
          end

        if @user.blocked
            redirect_to new_session_path, alert:"Usuario bloqueado."    
            return    
        end

        if @user&.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to "/"
        else
            redirect_to new_session_path, alert:"Credenciales incorrectas." 
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to new_session_path
    end

    private

    def logged_in?  # Helper method for checking session
        session[:user_id].present?
    end

    def require_no_authentication  # Before action to enforce validation
        redirect_to "/", alert: "Ya has iniciado sesión." if logged_in?
    end

    before_action :require_no_authentication, only: [:new, :create]

end

app/controllers/authentication/users_controller.rb
class Authentication::UsersController < ApplicationController
    skip_before_action :protect_route, only: [:new, :create]
    def new
        @user=User.new
    end
    def create
        @user=User.new(user_params.merge(rol:'user',blocked:false))
        if @user.save
            redirect_to "/"
        else
            render :new, status: :unprocessable_entity
        end
    end
    def show
        @user = User.find(params[:id])
    end
    def edit
        @user = User.find(params[:id])
    end
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to edit_user_path(params[:id]), notice:'Usuario editada correctamente.'
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private 
    
    def user_params
        params.require(:user).permit(:email,:name,:lastname,:email,:password,:rol,:blocked,:img)
    end
    def logged_in?
        session[:user_id].present?
    end
    def require_no_authentication 
        redirect_to "/", alert: "Ya has iniciado sesión." if logged_in?
    end
    before_action :require_no_authentication, only: [:create, :new]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
    @comment = Comment.new(content:params[:content], publication_id:params[:id], user_id:Current.user.id)

      if @comment.save
        # redirect_to 
      else
        flash[:error] = "Failed to create comment: #{@comment.errors.full_messages.join(', ')}"
        render :new, status: :unprocessable_entity
      end
    end
  
    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      redirect_to
    end

    private
  
    def comment_params
      params.require(:comment).permit(:content)
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :protect_route, only: [:index]
  include Pagy::Backend

  def index
    @pagy, @records = pagy(Publication.all)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

    skip_before_action :protect_route

    def new
    end

    def create
        @user = User.find_by(email:params[:email])
        if @user.present?
            PasswordMailer.with(user:@user).reset.deliver_now
        else
        end
        redirect_to "/", notice:"Si existe un usuario se envio correo de recuperacion."
    end

    def edit
    
        @user = User.find_signed!(params[:token], purpose:"password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to "/", alert:"Token invalido"
    end

    def update
        @user = User.find_signed!(params[:token], purpose:"password_reset")
        if(@user.update(password_params))
            redirect_to sessions_path, notice:"Contrasena actualizada"
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirm)
    end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  skip_before_action :protect_route, only: [:show,]
  def show
    @publication = Publication.find(params[:id])
  end
  def new
    @publication = Publication.new
  end
  def create
    @publication = Publication.new(
      publication_params.merge(
        blocked: false,
      )
    )

    if @publication.save
      redirect_to "/", notice:'Publicacion creada correctamente.'
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    @publication = Publication.find(params[:id])
  end
  def update
    @publication = Publication.find(params[:id])
    if @publication.update(publication_params)
      redirect_to "/", notice:'Publicacion editada correctamente.'
    else
      render :new, status: :unprocessable_entity
    end
  end
  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy
    redirect_to "/", notice:"Publicacion eliminada correctamente.", status: :see_other
  end
  private
  def publication_params
    params.require(:publication).permit(:title,:content,:blocked,:image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    include Pagy::Frontend

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/authentication/users/edit.html.erb
<div class="h-full pb-20 flex flex-col justify-center items-center">
    <div class="w-[33vw] flex flex-col gap-4 items-center bg-[#D9D9D9] px-8 py-6 shadow border border-1 border-[#D9D9D9] rounded">
        <div class="w-full flex justify-between">
            <%= link_to "Volver", user_path(Current.user.id), class:"self-start"%>
        </div>
        <%= form_with model: @user,  html:{class:"w-full flex flex-col gap-3"} do |form| %>
            <% @user.errors.full_messages.each do |error|%>
                <p><%= error%></p>
            <%end%>
            <div class="flex flex-col gap-3 items-center">
                <p>Foto de perfil</p>
                <%= image_tag @user.img ,class: 'w-[8em] h-[8em] rounded-full', id:"user_image_tag" if @user.img.attached?%>
                <%= form.file_field :img, class:"hidden" %>
            </div>
            <div class="w-full grid grid-cols-2 gap-3">
                <div class="flex flex-col gap-2">
                    <%= form.label :name %>
                    <%= form.text_field :name, class:"bg-slate-100 px-3 py-2 rounded", placeholder:"Nombre" %>
                </div>
                <div class="flex flex-col gap-2">
                    <%= form.label :lastname %>
                    <%= form.text_field :lastname, class:"bg-slate-100 px-3 py-2 rounded", placeholder:"Apellido" %>
                </div>
                <div class="flex flex-col gap-2 col-span-2">
                        <%= form.label :email %>
                        <%= form.email_field :email, class:"bg-slate-100 px-3 py-2 rounded", placeholder:"Correo" %>
                </div>
            </div>
            <%= form.submit "Editar", class:"text-sm self-end border border-1 border-black rounded py-2 px-4"%>
        <%end%>
    </div>
    <script src="<%= asset_path('edit user.js') %>"></script>
</div>

app/views/authentication/users/new.html.erb
<div class="h-full pb-20 flex flex-col justify-center items-center">
    <div class="flex flex-col gap-2 items-center bg-[#D9D9D9] px-8 py-6 shadow border border-1 border-[#D9D9D9] rounded">
        <div class="w-full flex gap-4 justify-start items-center">
            <small>
                <%= link_to "Volver", new_session_path %>
            </small>
            <big>
                <h1 class="text-xl">Registro</h1>
            </big>
        </div>
        <%= form_with model: @user, html:{class:"flex flex-col gap-4"} do |form| %>
            <% @user.errors.full_messages.each do |error|%>
                <p><%= error%></p>
            <%end%>
            <div class="flex flex-col gap-2 items-center">
                <%= form.label :img, "Foto de perfil", class:"text-center" %>
                <%= form.file_field :img, label:"Foto de perfil" , class:"hidden"%>
                <img id="avatar-register-img" class="w-[7em] h-[7em] rounded-full cursor-pointer border-gray-400 border-1 border"/>
            </div>
            <div class="grid grid-cols-2 gap-2">
                <div class="flex flex-col gap-2">
                    <%= form.label :name %>
                    <%= form.text_field :name, class:"border border-1 border-gray-300 rounded", placeholder:"Nombre" %>
                </div>
                <div class="flex flex-col gap-2">
                    <%= form.label :lastname %>
                    <%= form.text_field :lastname, class:"border border-1 border-gray-300 rounded", placeholder:"Apellido" %>

                </div>
                <div class="flex flex-col gap-2">
                    <%= form.label :email %>
                    <%= form.email_field :email, class:"border border-1 border-gray-300 rounded", placeholder:"Correo"  %>
                </div>
                <div class="flex flex-col gap-2">
                    <%= form.label :password %>
                    <%= form.password_field :password, class:"border border-1 border-gray-300 rounded", placeholder:"Contrasena" %>
                </div>
            </div>
            <%= form.submit "Registrar", class:"text-sm self-end border border-1 border-black rounded py-2 px-4"%>
        <%end%>
    </div>
    <script src="<%= asset_path('register.js') %>"></script>
</div>

app/views/authentication/users/show.html.erb
<div class="h-full pb-20 flex flex-col justify-center items-center">
    <div class="w-[33vw] flex flex-col gap-4 items-center bg-[#D9D9D9] px-8 py-6 shadow border border-1 border-[#D9D9D9] rounded">
        <div class="w-full flex justify-between">
            <%= link_to "Inicio", "/", class:"self-start" if Current.user.id.to_s == params[:id].to_s%>
            <%= link_to "Editar perfil", edit_user_path(params[:id]), class:"self-start" if Current.user.id.to_s == params[:id].to_s%>
        </div>
        <div class="flex flex-col gap-3 items-center">
            <p>Foto de perfil</p>
            <%= image_tag @user.img ,class: 'w-[8em] h-[8em] rounded-full' if @user.img.attached?%>
        </div>
        <div class="w-full grid grid-cols-2 gap-3">
            <div class="flex flex-col gap-2">
                <p>Nombre</p>
                <p class="bg-slate-100 px-3 py-2 rounded">
                    <%=@user.name%>
                </p>
            </div>
            <div class="flex flex-col gap-2">
                <p>Apellido</p>
                <p class="bg-slate-100 px-3 py-2 rounded"><%=@user.lastname%></p>
            </div>
            <div class="flex flex-col gap-2 col-span-2">
                <p>Correo</p>
                <p class="bg-slate-100 px-3 py-2 rounded"><%=@user.email%></p>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="w-full">
   <%= link_to "Crear publicaciones", new_publication_path%>
  <div class="flex flex-col items-center gap-5">
  <%@records.each do |publication| %>
    <div class="flex flex-col gap-2">
      <%= link_to user_path(publication.user.id) do%>
        <div class="flex gap-1 items-center">
          <%= image_tag publication.user.img ,class: 'w-7 h-7 rounded-full' if publication.user.img.attached?%>
          <p><%=publication.user.name%></p>
          <p><%=publication.user.lastname%></p>
        </div>
      <%end%> 
      <%= link_to publication_path(publication.id) do %>
        <%= image_tag publication.image ,class: 'w-[25vw] rounded' if publication.image.attached?%>
        <div class="flex flex-col gap-0">
          <p class="max-w-[25vw]"><%= publication.title%></p>
          <small class="max-w-[25vw]"><%= publication.content%></small>
        </div>
      <%end%>
    <hr class="w-full rounded">
    </div>
  <%end%>
  <%== pagy_nav(@pagy) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyOnRailApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen">
    <header class="h-[5%] px-8 py-2 bg-gray-200">
      <nav class="h-full">
        <div class="h-full flex justify-between items-center">
          <a href="/">
            <p>Logo</p>
          </a>
          <div class="flex gap-4 items-center">
            <%= link_to "Perfil", users_path+"/"+Current.user.id.to_s if Current.user%>
            <%= link_to "Admin", "/motor_admin/" if Current.user && Current.user.rol == "admin"%>
            <%= link_to "Cerrar sesion", sessions_path + "/0", data:{turbo_method: :delete} if Current.user%>    
            <%= link_to "Iniciar sesion", "sessions/new" if !Current.user%>
          </div>
        </div>
      </nav>
    </header>
    <main class="h-[90%] px-8 py-4">
      <%= yield %>
      <%=notice%>
      <%=alert%>
    </main>
  </body>
</html>

app/views/password_resets/edit.html.erb
<div class="h-full pb-20 flex flex-col justify-center items-center">
    <div class="flex flex-col gap-4 items-center bg-[#D9D9D9] px-6 py-4 shadow border border-1 border-[#D9D9D9] rounded">
        <h1>Restaurar contrasena</h1>
        <%= form_with model:@user, url: password_reset_edit_path(token: params[:token]), html:{class:"flex flex-col gap-4"} do |form|%>
            <small class="">
                Restaure su contraseña.
            </small>
            <div class="flex flex-col gap-1">
                <%= form.label :password, "Nueva contrasena" %>
                <%= form.password_field :password, class:"border border-1 border-gray-300 rounded" %>
            </div>
            <%= form.submit "Confirmar" ,class:"text-sm self-end border border-1 border-black rounded py-2 px-4"%>
        <% end%>
    </div>
</div>

app/views/password_resets/new.html.erb
<div class="h-full pb-20 flex flex-col justify-center items-center">
    <div class="flex flex-col gap-4 items-center bg-[#D9D9D9] px-6 py-4 shadow border border-1 border-[#D9D9D9] rounded">
        <h1>Recuperar contrasena</h1>
        <%= form_with url: password_reset_path, html:{class:"flex flex-col gap-4"} do |form|%>
            <small class="">
                Ingrese su correo electronico. Si este corresponde <br> con alguno registrado,
                se le enviara un correo para <br> que pueda restarurar su contraseña.
            </small>
            <div class="flex flex-col gap-1">
                <%= form.label :email %>
                <%= form.email_field :email, class:"border border-1 border-gray-300 rounded" %>
            </div>
            <%= form.submit "Confirmar" ,class:"text-sm self-end border border-1 border-black rounded py-2 px-4"%>
        <% end%>
    </div>
</div>

app/views/publications/edit.html.erb
<div class="h-full pb-20 flex flex-col justify-center items-center">
    <div class="w-[33vw] flex flex-col gap-4 items-center bg-[#D9D9D9] px-8 py-6 shadow border border-1 border-[#D9D9D9] rounded">
        <div class="w-full flex justify-between">
            <%= link_to "Volver", "/"%>
        </div>

        <%= form_with model: @publication, html:{class:"flex flex-col gap-4"} do |form| %>
            <% @publication.errors.full_messages.each do |error|%>
                <p><%= error %></p>
            <%end%> 
            <%= form.file_field :image, label:"Foto de perfil" , class:"hidden"%>
            <img id="avatar-register-img" class="w-[30vw] h-[15em] rounded cursor-pointer border-white border-1 border bg-white"/>
            <%= form.file_field :image, class:"hidden" %>
            <%= form.label :title %>
            <%= form.text_field :title, class:"border border-1 border-gray-300 rounded", placeholder:"Titulo" %>
            <%= form.label :content %>
            <%= form.text_area :content, class:"border border-1 border-gray-300 rounded",placeholder:"Contenido" %>
            <%= form.submit "Editar", class:"text-sm self-end border border-1 border-black rounded py-2 px-4"%>
        <%end%>
    </div>
    <script src="<%= asset_path('publication.js') %>"></script>
</div>

app/views/publications/index.html.erb
<div class="bg-black">
    <h1>PUBLICACIONES</h1>
</div>

app/views/publications/new.html.erb
<div class="h-full pb-20 flex flex-col justify-center items-center">
    <div class="flex flex-col gap-8 items-center bg-[#D9D9D9] px-6 py-4 shadow border border-1 border-[#D9D9D9] rounded">        
        <big class="flex justify-start w-full gap-3">
            <%= link_to "Volver", "/"%>
            <h1 class="text-xl">Crear publicacion</h1>
        </big>
        <%= form_with model: @publication, html:{class:"flex flex-col gap-4"} do |form| %>
            <% @publication.errors.full_messages.each do |error|%>
                <p><%= error%></p>
            <%end%>
            <div class="flex flex-col gap-2 items-center">
                <%= form.file_field :image, label:"Foto de perfil" , class:"hidden"%>
                <img id="avatar-register-img" class="w-[30vw] h-[15em] rounded cursor-pointer border-white border-1 border bg-white"/>
            </div>
            <%= form.label :title %>
            <%= form.text_field :title, class:"border border-1 border-gray-300 rounded", placeholder:"Titulo" %>
            <%= form.label :content %>
            <%= form.text_area :content, class:"border border-1 border-gray-300 rounded", placeholder:"Contenido" %>
            <%= form.submit "Crear", class:"text-sm self-end border border-1 border-black rounded py-2 px-4"%>
        <%end%>
    </div>
     <script src="<%= asset_path('publication.js') %>"></script>
</div>

app/views/publications/show.html.erb
<div class="flex justify-center gap-20">
    <div class="w-[33%] flex flex-col gap-2">
        <div class="flex justify-between items-center">
            <%= link_to user_path(@publication.user.id) do%>
                <div class="flex gap-1 items-center">
                    <%= image_tag @publication.user.img ,class: 'w-7 h-7 rounded-full' if @publication.user.img.attached?%>
                    <p><%=@publication.user.name%></p>
                    <p><%=@publication.user.lastname%></p>
                </div>
            <%end%> 
            <small>
                <% if Current.user %>
                    <%=link_to "Editar publicacion", edit_publication_path(@publication)  if Current.user.id.to_s ==  @publication.user.id.to_s %>
                    <%= form_with model: @publication, method: :delete, html: { class: "flex flex-col gap-4" } do |form|%>
                        <%= hidden_field_tag :_method, :delete %>  <%= form.submit "Eliminar", class:"text-sm self-end bg-red-500 text-white rounded py-2 px-4" %>
                    <% end %>
                <% end %>
            </small>
        </div>
        <%= image_tag @publication.image if @publication.image.attached?%>
        <p><%=@publication.title%></p>
        <small><%=@publication.content%></small>
    </div>
    <p>
        Usuario
        <%=Current.user%>
    </p>
    <div class="flex flex-col gap-2">
        <% @publication.comments.each do |comment|%>
            <div class="flex items-center gap-3">
                <%= link_to user_path(comment.user_id) do%>
                    <%= image_tag comment.user.img ,class: 'w-7 h-7 rounded-full' if comment.user.img.attached?%>
                <%end%> 
                <div class="w-full flex flex-col gap-1">
                    <small class="w-full flex justify-between">
                        <%= link_to user_path(comment.user_id) do%>
                            <%= comment.user.name%>
                         <%end%> 
                        <%=link_to "Eliminar comentario", "/comments/"+comment.id.to_s, data:{
                            turbo_method: :delete
                        }%>
                    </small>
                    <%= comment.content%>
                </div>
            </div>
            <hr>
        <% end %>
         <% if Current.user %>
            <%= form_with model: @comment,  html:{class:"flex justify-between gap-5 items-center"}, url:"/comments/"+@publication.id.to_s  do |f| %>
                    <div class="flex flex-col">
                        <%= f.text_field :content, placeholder:"Comentar",class:"border border-none rounded"%>
                    </div>
                    <div>
                        <%= f.submit "Publicar" %>
                    </div>
            <% end %>
        <% end %>
    </div>
</div>